name: Release

on:
  push:

env:
  SOLUTION_NAME: RocketLounge
  DLL_NAME: A1RocketLounge

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
      with:
        path: plugin

    - name: Clone BakkesmodSDK
      uses: actions/checkout@v3
      with:
        repository: bakkesmodorg/BakkesModSDK
        path: plugin\bakkesmodsdk

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Install Deps
      run: .\Setup.ps1
      working-directory: plugin

    - name: Build
      run: msbuild /m /p:Configuration=Release /p:BakkesModPath=$env:GITHUB_WORKSPACE\plugin /p:Environment=GitHub $env:GITHUB_WORKSPACE\plugin\${{ env.SOLUTION_NAME }}.sln

    - name: Zip
      uses: vimtor/action-zip@v1
      with:
        files: plugin\plugins\${{ env.DLL_NAME }}.dll
        dest: ${{ env.DLL_NAME }}.zip

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: "${{ env.GITHUB_TOKEN }}"
        prerelease: false
        files: ${{ env.DLL_NAME }}.zip

    - name: Create Pre-Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      if: github.ref_name == 'main'
      with:
        repo_token: "${{ env.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: ${{ env.DLL_NAME }}.zip